name: ReSharper code cleanup

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    if: contains(github.event.push.commits.*.message, '[AUTO]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: .NET setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: dotnet build -c Release
    - name: ReSharper tools setup
      run: dotnet tool install --global JetBrains.ReSharper.GlobalTools --version 2021.3.0-eap07
    - name: Code cleanup
      run: jb cleanupcode --profile=Full --properties:Configuration=Release AInq.Bitrix24.sln
    - name: Git DIFF
      id: git-diff
      run: echo ::set-output name=modified::$(if git diff-index --quiet --ignore-cr-at-eol HEAD ; then echo "false"; else echo "true"; fi)
    - name: Setup GPG
      if: steps.git-diff.outputs.modified == 'true'
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Push changes
      if: steps.git-diff.outputs.modified == 'true'
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -S -a -m "[AUTO] Code cleanup"
        git push
